import "./globals.css";
import { Roboto } from "next/font/google";
import Nav from "./auth/Nav";
import QueryWrapper from "./auth/QueryWrapper";

export const metadata = {
  title: "Posty App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` mx-4 md:mx-49 xl:mx-96 ${roboto.variable} bg-gray-300`}
      >
        <QueryWrapper>
          <Nav />
          {children}
        </QueryWrapper>
      </body>
    </html>
  );
}
